name: $(BuildID)
pr:
  autoCancel: false
  branches:
    include:
      - '*'
trigger:
  batch: false
  branches:
    include:
      - '*'
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Maven@3
            name: Install_Parent
            inputs:
              mavenPomFile: ./nexuse2e-parent/pom.xml
              goals: clean install
              options: >
                -B -e --no-transfer-progress 
              publishJUnitResults: false
              javaHomeOption: JDKVersion
              jdkVersionOption: 1.11
              jdkArchitectureOption: 'x64'
              mavenOptions: '-Xmx3072m'
              mavenAuthenticateFeed: true
          - task: Maven@3
            name: Build_core
            inputs:
              mavenPomFile: ./nexuse2e-core/pom.xml
              goals: clean install
              options: >
                -B -e --no-transfer-progress
              publishJUnitResults: false
              javaHomeOption: JDKVersion
              jdkVersionOption: 1.11
              jdkArchitectureOption: 'x64'
              mavenOptions: '-Xmx3072m'
              mavenAuthenticateFeed: true
          - task: CopyPublishBuildArtifacts@1
            inputs:
              Contents: 'nexuse2e-core/target/*.jar'
              ArtifactName: 'core'
              ArtifactType: 'Container'
          - task: Maven@3
            name: Build_webapp
            inputs:
              mavenPomFile: ./nexuse2e-webapp/pom.xml
              goals: clean verify
              options: >
                -B -e -P with-new-frontend --no-transfer-progress
              publishJUnitResults: false
              javaHomeOption: JDKVersion
              jdkVersionOption: 1.11
              jdkArchitectureOption: 'x64'
              mavenOptions: '-Xmx3072m'
              mavenAuthenticateFeed: true
          - task: CopyPublishBuildArtifacts@1
            inputs:
              Contents: 'nexuse2e-webapp/target/*.war'
              ArtifactName: 'webapp'
              ArtifactType: 'Container'
